spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/credit-card-student?serverTimezone=UTC"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
  batch:
    jdbc:
      initialize-schema: always
      platform: mysql

integration:
  file:
    students:
      source: lista_alunos.txt
      load: true   # Make true to load initial batch load from students
      chunk-size: 1000