spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/credit-card-student?serverTimezone=UTC"
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    initialization-mode: "always"
